services:
  postgres:
    image: postgres:15-alpine
    container_name: cozy_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - cozy_postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: cozy_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    volumes:
      - cozy_minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  cozy_postgres_data:
  cozy_minio_data:
